# Start AeroSpace at login
start-at-login = true 

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 300

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Discord'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Notes'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Spotify'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Docker Desktop'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'pgAdmin 4'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Apidog'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Microsoft Edge'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chrome'
run = 'move-node-to-workspace 3'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        10
outer.right =      20

[mode.main.binding]

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

alt-shift-left = 'join-with left'
alt-shift-down = 'join-with down'
alt-shift-up = 'join-with up'
alt-shift-right = 'join-with right'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
alt-shift-enter = 'mode apps'

alt-g = ['exec-and-forget open -a /Applications/Ghostty.app', 'workspace 1']


[workspace-to-monitor-force-assignment]
1 = ['24G1WG4', 'secondary']

2 = ['24G1WG4', 'secondary']

3 = 'main'

4 = 'main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]

# test stow
